#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("quemECeu.Resource", IsApplication=true)]

namespace quemECeu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bonecoCeuense = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int morador1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int morador10 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int morador100 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int morador101 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int morador102 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int morador103 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int morador104 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int morador105 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int morador106 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int morador107 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int morador108 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int morador11 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int morador111 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int morador112 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int morador113 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int morador114 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int morador115 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int morador117 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int morador118 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int morador120 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int morador121 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int morador122 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int morador123 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int morador124 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int morador125 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int morador128 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int morador129 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int morador13 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int morador130 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int morador131 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int morador133 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int morador134 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int morador135 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int morador136 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int morador137 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int morador138 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int morador139 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int morador140 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int morador141 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int morador142 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int morador143 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int morador144 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int morador145 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int morador146 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int morador147 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int morador148 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int morador149 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int morador15 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int morador150 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int morador151 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int morador152 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int morador153 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int morador154 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int morador155 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int morador156 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int morador157 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int morador158 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int morador159 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int morador16 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int morador160 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int morador161 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int morador162 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int morador163 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int morador164 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int morador165 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int morador166 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int morador167 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int morador168 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int morador169 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int morador17 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int morador172 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int morador173 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int morador174 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int morador176 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int morador177 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int morador179 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int morador18 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int morador180 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int morador181 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int morador183 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int morador186 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int morador188 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int morador189 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int morador190 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int morador191 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int morador192 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int morador193 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int morador194 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int morador195 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int morador196 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int morador197 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int morador198 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int morador199 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int morador2 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int morador20 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int morador200 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int morador201 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int morador202 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int morador204 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int morador205 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int morador207 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int morador208 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int morador209 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int morador21 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int morador210 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int morador211 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int morador212 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int morador213 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int morador214 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int morador215 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int morador216 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int morador218 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int morador219 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int morador222 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int morador223 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int morador224 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int morador225 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int morador226 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int morador227 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int morador228 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int morador229 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int morador23 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int morador230 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int morador231 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int morador232 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int morador233 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int morador234 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int morador235 = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int morador237 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int morador238 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int morador239 = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int morador24 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int morador242 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int morador243 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int morador245 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int morador246 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int morador247 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int morador25 = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int morador26 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int morador27 = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int morador28 = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int morador29 = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int morador3 = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int morador30 = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int morador31 = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int morador33 = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int morador34 = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int morador36 = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int morador37 = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int morador38 = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int morador39 = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int morador41 = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int morador42 = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int morador44 = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int morador45 = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int morador46 = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int morador49 = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int morador5 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int morador50 = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int morador51 = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int morador52 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int morador54 = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int morador56 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int morador57 = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int morador58 = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int morador59 = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int morador6 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int morador60 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int morador61 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int morador62 = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int morador63 = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int morador64 = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int morador65 = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int morador66 = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int morador67 = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int morador68 = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int morador69 = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int morador7 = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int morador70 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int morador71 = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int morador72 = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int morador73 = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int morador74 = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int morador76 = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int morador77 = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int morador78 = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int morador79 = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int morador81 = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int morador82 = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int morador83 = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int morador84 = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int morador85 = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int morador86 = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int morador87 = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int morador88 = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int morador89 = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int morador9 = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int morador90 = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int morador92 = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int morador93 = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int morador94 = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int morador97 = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int morador99 = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int trofeuBronze = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int trofeuDourado = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int trofeuPrata = 2130837712;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int bonecoCeuense = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int comecar = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int enviar = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int foto = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int opcoes = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int pontuacao = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int radioButton1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int radioButton2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int radioButton3 = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int tempo = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int tentativasErradas = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int titulo = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int tituloPontuacao = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int tituloTempo = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int tituloTentativaErradas = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int trofeu = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Pontuacao = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TelaInicial = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int enviar = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int pontuacao = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int titulo = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int tituloPontuacao = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int tituloTempo = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int tituloTentativaErradas = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
