using System.Collections.Generic;

namespace quemECeu
{
    class Ceuense
    {
        public int id { get; set; }
        public string nome { get; set; }
        public char sexo { get; set; }
        public int foto { get; set; }
        public List<Ceuense> gerarLista()
        {
            List<Ceuense> morador = new List<Ceuense>();
            #region Lista de Moradores
            //Lista Completa sem intercâmbio
            //morador.Add(new Ceuense { id = 0, nome = "Adonias Alfredo Carvalho", sexo = 'm', sexo = 'm', foto = Resource.Drawable.morador0 });
            morador.Add(new Ceuense { id = 1, nome = "Alan Diego Soares Ribeiro", sexo = 'm', foto = Resource.Drawable.morador1 });
            morador.Add(new Ceuense { id = 2, nome = "Alan Martins", sexo = 'm', foto = Resource.Drawable.morador2 });
            morador.Add(new Ceuense { id = 3, nome = "Alane Marie De Lima", sexo = 'f', foto = Resource.Drawable.morador3 });
            //morador.Add(new Ceuense { id = 4, nome = "Alessandra Aguiar De Andrade", sexo = 'f', foto = Resource.Drawable.morador4 });
            morador.Add(new Ceuense { id = 5, nome = "Alex Tadeu Moreira Santos", sexo = 'm', foto = Resource.Drawable.morador5 });
            morador.Add(new Ceuense { id = 6, nome = "Alexandre Augusto Sojo Tavares Ávila", sexo = 'm', foto = Resource.Drawable.morador6 });
            morador.Add(new Ceuense { id = 7, nome = "Aline Beserra De Morais", sexo = 'f', foto = Resource.Drawable.morador7 });
            //morador.Add(new Ceuense { id = 8, nome = "Alisson José Castro Medeiros", sexo = 'm', foto = Resource.Drawable.morador8 });
            morador.Add(new Ceuense { id = 9, nome = "Allan Gomes", sexo = 'm', foto = Resource.Drawable.morador9 });
            morador.Add(new Ceuense { id = 10, nome = "Amanda Alves Ferreira", sexo = 'f', foto = Resource.Drawable.morador10 });
            morador.Add(new Ceuense { id = 11, nome = "Amilly Bárbara Faria Machado", sexo = 'f', foto = Resource.Drawable.morador11 });
            //morador.Add(new Ceuense { id = 12, nome = "Ana Paula Cecere Santana", sexo = 'f', foto = Resource.Drawable.morador12 });
            morador.Add(new Ceuense { id = 13, nome = "André Nogueira", sexo = 'm', foto = Resource.Drawable.morador13 });
            //morador.Add(new Ceuense { id = 14, nome = "Antonio Lucas Pires Nunes Pinto", sexo = 'm', foto = Resource.Drawable.morador14 });
            morador.Add(new Ceuense { id = 15, nome = "Antony Cesar Santos Cavalcante", sexo = 'm', foto = Resource.Drawable.morador15 });
            morador.Add(new Ceuense { id = 16, nome = "Arnaldo Souza E Silva Junior", sexo = 'm', foto = Resource.Drawable.morador16 });
            morador.Add(new Ceuense { id = 17, nome = "Arthur Aquino Lino De Souza", sexo = 'm', foto = Resource.Drawable.morador17 });
            morador.Add(new Ceuense { id = 18, nome = "Barbra Eliza Domingues Da Silva", sexo = 'f', foto = Resource.Drawable.morador18 });
            //morador.Add(new Ceuense { id = 19, nome = "Benedito Maurilio Fagundes", sexo = 'm', foto = Resource.Drawable.morador19 });
            morador.Add(new Ceuense { id = 20, nome = "Bruna Carolina Coutinho", sexo = 'f', foto = Resource.Drawable.morador20 });
            morador.Add(new Ceuense { id = 21, nome = "Bruna Luisa Antunes", sexo = 'f', foto = Resource.Drawable.morador21 });
            //morador.Add(new Ceuense { id = 22, nome = "Bruno Fornari Barcelos", sexo = 'm', foto = Resource.Drawable.morador22 });
            morador.Add(new Ceuense { id = 23, nome = "Bruno Henrique Veras Dantas", sexo = 'm', foto = Resource.Drawable.morador23 });
            morador.Add(new Ceuense { id = 24, nome = "Bruno Novak", sexo = 'm', foto = Resource.Drawable.morador24 });
            morador.Add(new Ceuense { id = 25, nome = "Camila De França Guimarães", sexo = 'f', foto = Resource.Drawable.morador25 });
            morador.Add(new Ceuense { id = 26, nome = "Carla Milena Pereira", sexo = 'f', foto = Resource.Drawable.morador26 });
            morador.Add(new Ceuense { id = 27, nome = "Carlos Eduardo Gonçalves Fernandes", sexo = 'm', foto = Resource.Drawable.morador27 });
            morador.Add(new Ceuense { id = 28, nome = "Cassio Henrique Gonçalves", sexo = 'm', foto = Resource.Drawable.morador28 });
            morador.Add(new Ceuense { id = 29, nome = "Celso Arideus De Farias", sexo = 'm', foto = Resource.Drawable.morador29 });
            morador.Add(new Ceuense { id = 30, nome = "Cintia Maria Leal Da Silva", sexo = 'f', foto = Resource.Drawable.morador30 });
            morador.Add(new Ceuense { id = 31, nome = "Cláudia Santos Silva", sexo = 'f', foto = Resource.Drawable.morador31 });
            //morador.Add(new Ceuense { id = 32, nome = "Cleberton Pereira De Sousa", sexo = 'm', foto = Resource.Drawable.morador32 });
            morador.Add(new Ceuense { id = 33, nome = "Cleidiane Rosário Andrade", sexo = 'f', foto = Resource.Drawable.morador33 });
            morador.Add(new Ceuense { id = 34, nome = "Cleriston Augusto Simette", sexo = 'm', foto = Resource.Drawable.morador34 });
            //morador.Add(new Ceuense { id = 35, nome = "Cleverton De Quadros", sexo = 'm', foto = Resource.Drawable.morador35 });
            morador.Add(new Ceuense { id = 36, nome = "Crislaine Franco Da Rocha", sexo = 'f', foto = Resource.Drawable.morador36 });
            morador.Add(new Ceuense { id = 37, nome = "Cristiano Teixeira De Sousa", sexo = 'm', foto = Resource.Drawable.morador37 });
            morador.Add(new Ceuense { id = 38, nome = "Daiane Alícia Lohse", sexo = 'f', foto = Resource.Drawable.morador38 });
            morador.Add(new Ceuense { id = 39, nome = "Dalton Menezes Da Costa", sexo = 'm', foto = Resource.Drawable.morador39 });
            //morador.Add(new Ceuense { id = 40, nome = "Daniel Mauricio Pedernera Parada", sexo = 'm', foto = Resource.Drawable.morador40 });
            morador.Add(new Ceuense { id = 41, nome = "Daniel Negoseki Robalo Costa", sexo = 'm', foto = Resource.Drawable.morador41 });
            morador.Add(new Ceuense { id = 42, nome = "Daniel Renan Duarte Alves Lima", sexo = 'm', foto = Resource.Drawable.morador42 });
            //morador.Add(new Ceuense { id = 43, nome = "Daniela Dos Reis Silva", sexo = 'f', foto = Resource.Drawable.morador43 });
            morador.Add(new Ceuense { id = 44, nome = "Danilo Santiago Carlos", sexo = 'm', foto = Resource.Drawable.morador44 });
            morador.Add(new Ceuense { id = 45, nome = "David Gabriel Ferreira Jazinski", sexo = 'm', foto = Resource.Drawable.morador45 });
            morador.Add(new Ceuense { id = 46, nome = "Denilson Dionisio", sexo = 'm', foto = Resource.Drawable.morador46 });
            //morador.Add(new Ceuense { id = 47, nome = "Denis Alves Dias", sexo = 'm', foto = Resource.Drawable.morador47 });
            //morador.Add(new Ceuense { id = 48, nome = "Diego Armando Pinheiro Brito", sexo = 'm', foto = Resource.Drawable.morador48 });
            morador.Add(new Ceuense { id = 49, nome = "Diego Damasceno Bispo Da Silva", sexo = 'm', foto = Resource.Drawable.morador49 });
            morador.Add(new Ceuense { id = 50, nome = "Diego Das Neves De Souza", sexo = 'm', foto = Resource.Drawable.morador50 });
            morador.Add(new Ceuense { id = 51, nome = "Diogo Marcelo Das Chagas", sexo = 'm', foto = Resource.Drawable.morador51 });
            morador.Add(new Ceuense { id = 52, nome = "Domingos André Carlos", sexo = 'm', foto = Resource.Drawable.morador52 });
            //morador.Add(new Ceuense { id = 53, nome = "Douglas Ferreira Da Silva Vital", sexo = 'm', foto = Resource.Drawable.morador53 });
            morador.Add(new Ceuense { id = 54, nome = "Douglas Ismael Denck", sexo = 'm', foto = Resource.Drawable.morador54 });
            //morador.Add(new Ceuense { id = 55, nome = "Douglas Soares Vicente", sexo = 'm', foto = Resource.Drawable.morador55 });
            morador.Add(new Ceuense { id = 56, nome = "Eder Ariã Basso Correa Filho", sexo = 'm', foto = Resource.Drawable.morador56 });
            morador.Add(new Ceuense { id = 57, nome = "Eduardo Barbosa Feitosa Junior", sexo = 'm', foto = Resource.Drawable.morador57 });
            morador.Add(new Ceuense { id = 58, nome = "Eduardo Boneti Kubiack", sexo = 'm', foto = Resource.Drawable.morador58 });
            morador.Add(new Ceuense { id = 59, nome = "Eduardo De Andrade Borre", sexo = 'm', foto = Resource.Drawable.morador59 });
            morador.Add(new Ceuense { id = 60, nome = "Eduardo De Assis Pereira", sexo = 'm', foto = Resource.Drawable.morador60 });
            morador.Add(new Ceuense { id = 61, nome = "Eduardo Miguel Portella Ferreira", sexo = 'm', foto = Resource.Drawable.morador61 });
            morador.Add(new Ceuense { id = 62, nome = "Eduardo Nunes E Silva", sexo = 'm', foto = Resource.Drawable.morador62 });
            morador.Add(new Ceuense { id = 63, nome = "Eduardo Rafael Kobs", sexo = 'm', foto = Resource.Drawable.morador63 });
            morador.Add(new Ceuense { id = 64, nome = "Elis Ferrão Luge", sexo = 'm', foto = Resource.Drawable.morador64 });
            morador.Add(new Ceuense { id = 65, nome = "Elvis Roberto De Andrade", sexo = 'm', foto = Resource.Drawable.morador65 });
            morador.Add(new Ceuense { id = 66, nome = "Eric Henrique Moreira Evangelista", sexo = 'm', foto = Resource.Drawable.morador66 });
            morador.Add(new Ceuense { id = 67, nome = "Erick Mateus Pacheco Lopes", sexo = 'm', foto = Resource.Drawable.morador67 });
            morador.Add(new Ceuense { id = 68, nome = "Evandro Nogath Dobrichtop", sexo = 'm', foto = Resource.Drawable.morador68 });
            morador.Add(new Ceuense { id = 69, nome = "Everton Rocha Da Silva", sexo = 'm', foto = Resource.Drawable.morador69 });
            morador.Add(new Ceuense { id = 70, nome = "Ezequias Cloy Ferreira", sexo = 'm', foto = Resource.Drawable.morador70 });
            morador.Add(new Ceuense { id = 71, nome = "Ezequiel David", sexo = 'm', foto = Resource.Drawable.morador71 });
            morador.Add(new Ceuense { id = 72, nome = "Fábio André Ferreira Rangel", sexo = 'm', foto = Resource.Drawable.morador72 });
            morador.Add(new Ceuense { id = 73, nome = "Fabricio Camargo Maciel", sexo = 'm', foto = Resource.Drawable.morador73 });
            morador.Add(new Ceuense { id = 74, nome = "Fagner José Lirya Luiz", sexo = 'm', foto = Resource.Drawable.morador74 });
            //morador.Add(new Ceuense { id = 75, nome = "Felipe Da Silva", sexo = 'm', foto = Resource.Drawable.morador75 });
            morador.Add(new Ceuense { id = 76, nome = "Felipe Ellwanger Webers", sexo = 'm', foto = Resource.Drawable.morador76 });
            morador.Add(new Ceuense { id = 77, nome = "Felipe Martinhuk", sexo = 'm', foto = Resource.Drawable.morador77 });
            morador.Add(new Ceuense { id = 78, nome = "Felipe Stefanini Barbosa", sexo = 'm', foto = Resource.Drawable.morador78 });
            morador.Add(new Ceuense { id = 79, nome = "Fernando Aquiles Guinda", sexo = 'm', foto = Resource.Drawable.morador79 });
            //morador.Add(new Ceuense { id = 80, nome = "Fernando Boff", sexo = 'm', foto = Resource.Drawable.morador80 });
            morador.Add(new Ceuense { id = 81, nome = "Fernando Henrique De Almeida", sexo = 'm', foto = Resource.Drawable.morador81 });
            morador.Add(new Ceuense { id = 82, nome = "Fernando Trindade Santana", sexo = 'm', foto = Resource.Drawable.morador82 });
            morador.Add(new Ceuense { id = 83, nome = "Gabriel Domingues Da Silva", sexo = 'm', foto = Resource.Drawable.morador83 });
            morador.Add(new Ceuense { id = 84, nome = "Gabriel Moreira Da Silva De Souza", sexo = 'm', foto = Resource.Drawable.morador84 });
            morador.Add(new Ceuense { id = 85, nome = "Gabriel Moreira Ferreira", sexo = 'm', foto = Resource.Drawable.morador85 });
            morador.Add(new Ceuense { id = 86, nome = "Gabriel Teixeira Ferreira", sexo = 'm', foto = Resource.Drawable.morador86 });
            morador.Add(new Ceuense { id = 87, nome = "Gabriela De Araújo Modesto", sexo = 'f', foto = Resource.Drawable.morador87 });
            morador.Add(new Ceuense { id = 88, nome = "Gilberto Garcez De Oliveira Filho", sexo = 'm', foto = Resource.Drawable.morador88 });
            morador.Add(new Ceuense { id = 89, nome = "Gilson Litka", sexo = 'm', foto = Resource.Drawable.morador89 });
            morador.Add(new Ceuense { id = 90, nome = "Giovani Bertolla Sampaio", sexo = 'm', foto = Resource.Drawable.morador90 });
            //morador.Add(new Ceuense { id = 91, nome = "Gisleine De Oliveira Pinheiro", sexo = 'f', foto = Resource.Drawable.morador91 });
            morador.Add(new Ceuense { id = 92, nome = "Giulia Deltreggia Sartori", sexo = 'f', foto = Resource.Drawable.morador92 });
            morador.Add(new Ceuense { id = 93, nome = "Giuvane Litka", sexo = 'm', foto = Resource.Drawable.morador93 });
            morador.Add(new Ceuense { id = 94, nome = "Guilherme Alves Pereira", sexo = 'm', foto = Resource.Drawable.morador94 });
            //morador.Add(new Ceuense { id = 95, nome = "Guilherme Lemes De Souza", sexo = 'm', foto = Resource.Drawable.morador95 });
            //morador.Add(new Ceuense { id = 96, nome = "Guilherme Lourenço Da Silva", sexo = 'm', foto = Resource.Drawable.morador96 });
            morador.Add(new Ceuense { id = 97, nome = "Guilherme Rafael Ramos Da Quinta", sexo = 'm', foto = Resource.Drawable.morador97 });
            //morador.Add(new Ceuense { id = 98, nome = "Gustavo Flores Junker", sexo = 'm', foto = Resource.Drawable.morador98 });
            morador.Add(new Ceuense { id = 99, nome = "Gustavo Ramos Marques", sexo = 'm', foto = Resource.Drawable.morador99 });
            morador.Add(new Ceuense { id = 100, nome = "Higor Jezreel De Souza", sexo = 'm', foto = Resource.Drawable.morador100 });
            morador.Add(new Ceuense { id = 101, nome = "Iago Novais De Oliveira Ferreira", sexo = 'm', foto = Resource.Drawable.morador101 });
            morador.Add(new Ceuense { id = 102, nome = "Igo Levir Souza Rabelo", sexo = 'm', foto = Resource.Drawable.morador102 });
            morador.Add(new Ceuense { id = 103, nome = "Igor Kiyoshi Takashina", sexo = 'm', foto = Resource.Drawable.morador103 });
            morador.Add(new Ceuense { id = 104, nome = "Igor Pretti Silva", sexo = 'm', foto = Resource.Drawable.morador104 });
            morador.Add(new Ceuense { id = 105, nome = "Ildernon Vinicius Da Paixão Teixeira", sexo = 'm', foto = Resource.Drawable.morador105 });
            morador.Add(new Ceuense { id = 106, nome = "Isaac Saar Soares", sexo = 'm', foto = Resource.Drawable.morador106 });
            morador.Add(new Ceuense { id = 107, nome = "Isadora Alcântara Da Silva", sexo = 'f', foto = Resource.Drawable.morador107 });
            morador.Add(new Ceuense { id = 108, nome = "Ivandro Ribeiro Dos Santos De Castro", sexo = 'm', foto = Resource.Drawable.morador108 });
            //morador.Add(new Ceuense { id = 109, nome = "Jacques Mauriat Ngalemo Siankhe", sexo = 'm', foto = Resource.Drawable.morador109 });
            //morador.Add(new Ceuense { id = 110, nome = "Jaison Donizeti Da Silva", sexo = 'm', foto = Resource.Drawable.morador110 });
            morador.Add(new Ceuense { id = 111, nome = "Jarson Brenner Borges Passos", sexo = 'm', foto = Resource.Drawable.morador111 });
            morador.Add(new Ceuense { id = 112, nome = "Jean Ávila Rangel", sexo = 'm', foto = Resource.Drawable.morador112 });
            morador.Add(new Ceuense { id = 113, nome = "Jean Carlos Gorges", sexo = 'm', foto = Resource.Drawable.morador113 });
            morador.Add(new Ceuense { id = 114, nome = "Jeferson Silva Bispo De Araujo", sexo = 'm', foto = Resource.Drawable.morador114 });
            morador.Add(new Ceuense { id = 115, nome = "Jéssica Mabilde Dias", sexo = 'f', foto = Resource.Drawable.morador115 });
            //morador.Add(new Ceuense { id = 116, nome = "Jéssica Micheli Da Silva Miketen", sexo = 'f', foto = Resource.Drawable.morador116 });
            morador.Add(new Ceuense { id = 117, nome = "Joana Luzia Kulicz", sexo = 'f', foto = Resource.Drawable.morador117 });
            morador.Add(new Ceuense { id = 118, nome = "Joana Slompo", sexo = 'f', foto = Resource.Drawable.morador118 });
            //morador.Add(new Ceuense { id = 119, nome = "João Antonio Francisconi L. Thomé", sexo = 'm', foto = Resource.Drawable.morador119 });
            morador.Add(new Ceuense { id = 120, nome = "João Francisco Jagielski De Mira", sexo = 'm', foto = Resource.Drawable.morador120 });
            morador.Add(new Ceuense { id = 121, nome = "João Paulo Costa Benassi", sexo = 'm', foto = Resource.Drawable.morador121 });
            morador.Add(new Ceuense { id = 122, nome = "Johnny Lourenci Rodrigues", sexo = 'm', foto = Resource.Drawable.morador122 });
            morador.Add(new Ceuense { id = 123, nome = "Jorge Felipe Euriques", sexo = 'm', foto = Resource.Drawable.morador123 });
            morador.Add(new Ceuense { id = 124, nome = "Jorge José De Souza Faria", sexo = 'm', foto = Resource.Drawable.morador124 });
            morador.Add(new Ceuense { id = 125, nome = "Jorge Madson Santos Viana", sexo = 'm', foto = Resource.Drawable.morador125 });
            //morador.Add(new Ceuense { id = 126, nome = "José Dornela Filho", sexo = 'm', foto = Resource.Drawable.morador126 });
            //morador.Add(new Ceuense { id = 127, nome = "José Lucas Januário De Menezes", sexo = 'm', foto = Resource.Drawable.morador127 });
            morador.Add(new Ceuense { id = 128, nome = "José Luis Manrique Yañes", sexo = 'm', foto = Resource.Drawable.morador128 });
            morador.Add(new Ceuense { id = 129, nome = "Joséli Romovicz Fagundes", sexo = 'f', foto = Resource.Drawable.morador129 });
            morador.Add(new Ceuense { id = 130, nome = "Juliano Fogaça De Lima", sexo = 'm', foto = Resource.Drawable.morador130 });
            morador.Add(new Ceuense { id = 131, nome = "Julio Cesar Piaz", sexo = 'm', foto = Resource.Drawable.morador131 });
            //morador.Add(new Ceuense { id = 132, nome = "Junior Adriano Da Silva Santos", sexo = 'm', foto = Resource.Drawable.morador132 });
            morador.Add(new Ceuense { id = 133, nome = "Karen Luana Tonkelski", sexo = 'f', foto = Resource.Drawable.morador133 });
            morador.Add(new Ceuense { id = 134, nome = "Kelvin De Oliveira", sexo = 'm', foto = Resource.Drawable.morador134 });
            morador.Add(new Ceuense { id = 135, nome = "Keuri Ferigotti", sexo = 'm', foto = Resource.Drawable.morador135 });
            morador.Add(new Ceuense { id = 136, nome = "Koffi Dodzi Assigno", sexo = 'm', foto = Resource.Drawable.morador136 });
            morador.Add(new Ceuense { id = 137, nome = "Larissa Rodrigues Ribeiro", sexo = 'f', foto = Resource.Drawable.morador137 });
            morador.Add(new Ceuense { id = 138, nome = "Leandro Alves Ferreira", sexo = 'm', foto = Resource.Drawable.morador138 });
            morador.Add(new Ceuense { id = 139, nome = "Leandro Ribeiro Coelho", sexo = 'm', foto = Resource.Drawable.morador139 });
            morador.Add(new Ceuense { id = 140, nome = "Leonardo Barbosa Burgomeister", sexo = 'm', foto = Resource.Drawable.morador140 });
            morador.Add(new Ceuense { id = 141, nome = "Leonardo Batista De Santana", sexo = 'm', foto = Resource.Drawable.morador141 });
            morador.Add(new Ceuense { id = 142, nome = "Leonardo Da Silva Lopes Puras", sexo = 'm', foto = Resource.Drawable.morador142 });
            morador.Add(new Ceuense { id = 143, nome = "Leonardo Giehl", sexo = 'm', foto = Resource.Drawable.morador143 });
            morador.Add(new Ceuense { id = 144, nome = "Leonardo Saar Melo", sexo = 'm', foto = Resource.Drawable.morador144 });
            morador.Add(new Ceuense { id = 145, nome = "Lorraine Dias Da Silva", sexo = 'f', foto = Resource.Drawable.morador145 });
            //morador.Add(new Ceuense { id = 146, nome = "Lucas Basso Nakabayashi", sexo = 'm', foto = Resource.Drawable.morador146 });
            morador.Add(new Ceuense { id = 147, nome = "Lucas Camargo Maciel", sexo = 'm', foto = Resource.Drawable.morador147 });
            morador.Add(new Ceuense { id = 148, nome = "Lucas Cesar Lourenço De Moraes", sexo = 'm', foto = Resource.Drawable.morador148 });
            morador.Add(new Ceuense { id = 149, nome = "Lucas Daniel Custódio Praça", sexo = 'm', foto = Resource.Drawable.morador149 });
            morador.Add(new Ceuense { id = 150, nome = "Lucas Felipe  Pereira Cará", sexo = 'm', foto = Resource.Drawable.morador150 });
            morador.Add(new Ceuense { id = 151, nome = "Lucas Marques Colossal", sexo = 'm', foto = Resource.Drawable.morador151 });
            morador.Add(new Ceuense { id = 152, nome = "Lucas Paulino Feliciano", sexo = 'm', foto = Resource.Drawable.morador152 });
            morador.Add(new Ceuense { id = 153, nome = "Lucas Ribeiro Carvalho", sexo = 'm', foto = Resource.Drawable.morador153 });
            morador.Add(new Ceuense { id = 154, nome = "Lucas Scherbaty", sexo = 'm', foto = Resource.Drawable.morador154 });
            morador.Add(new Ceuense { id = 155, nome = "Luiz Felipe Inácio Dos Santos", sexo = 'm', foto = Resource.Drawable.morador155 });
            morador.Add(new Ceuense { id = 156, nome = "Luiz Filipe Dias Genesi", sexo = 'm', foto = Resource.Drawable.morador156 });
            morador.Add(new Ceuense { id = 157, nome = "Luiz Henrique Ross Palma", sexo = 'm', foto = Resource.Drawable.morador157 });
            morador.Add(new Ceuense { id = 158, nome = "Maicon Douglas Rodrigues", sexo = 'm', foto = Resource.Drawable.morador158 });
            morador.Add(new Ceuense { id = 159, nome = "Manuella Costa Pires", sexo = 'f', foto = Resource.Drawable.morador159 });
            morador.Add(new Ceuense { id = 160, nome = "Marcel William Bernabé G. De Almeida", sexo = 'm', foto = Resource.Drawable.morador160 });
            morador.Add(new Ceuense { id = 161, nome = "Marcela Mity Costa", sexo = 'f', foto = Resource.Drawable.morador161 });
            morador.Add(new Ceuense { id = 162, nome = "Marcelo Alberto De Oliveira", sexo = 'm', foto = Resource.Drawable.morador162 });
            morador.Add(new Ceuense { id = 163, nome = "Marcelo Augusto Correa Neri", sexo = 'm', foto = Resource.Drawable.morador163 });
            morador.Add(new Ceuense { id = 164, nome = "Marcelo Carvalho Rezende Faria", sexo = 'm', foto = Resource.Drawable.morador164 });
            morador.Add(new Ceuense { id = 165, nome = "Marcelo Pereira", sexo = 'm', foto = Resource.Drawable.morador165 });
            morador.Add(new Ceuense { id = 166, nome = "Marcelo Tadeu Dos Santos Junior", sexo = 'm', foto = Resource.Drawable.morador166 });
            morador.Add(new Ceuense { id = 167, nome = "Marcio Cunha Carlomagno", sexo = 'm', foto = Resource.Drawable.morador167 });
            morador.Add(new Ceuense { id = 168, nome = "Marco Antonio Amâncio Da Silva", sexo = 'm', foto = Resource.Drawable.morador168 });
            morador.Add(new Ceuense { id = 169, nome = "Marcos Daniel Lopes", sexo = 'm', foto = Resource.Drawable.morador169 });
            //morador.Add(new Ceuense { id = 170, nome = "Marcus Vinicius Da Silva Ramalho", sexo = 'm', foto = Resource.Drawable.morador170 });
            //morador.Add(new Ceuense { id = 171, nome = "Maria Fernanda Varela Bonilla", sexo = 'f', foto = Resource.Drawable.morador171 });
            morador.Add(new Ceuense { id = 172, nome = "Mariana Dos Santos Lobo", sexo = 'f', foto = Resource.Drawable.morador172 });
            morador.Add(new Ceuense { id = 173, nome = "Mário Sérgio Pereira", sexo = 'm', foto = Resource.Drawable.morador173 });
            morador.Add(new Ceuense { id = 174, nome = "Marlon Henrique Oliveira Ferreira", sexo = 'm', foto = Resource.Drawable.morador174 });
            //morador.Add(new Ceuense { id = 175, nome = "Martin Hajek", sexo = 'm', foto = Resource.Drawable.morador175 });
            morador.Add(new Ceuense { id = 176, nome = "Mateus Augusto Tavares", sexo = 'm', foto = Resource.Drawable.morador176 });
            morador.Add(new Ceuense { id = 177, nome = "Mateus De Jesus João Paulo Filho", sexo = 'm', foto = Resource.Drawable.morador177 });
            //morador.Add(new Ceuense { id = 178, nome = "Mauricio Tomim Saraiva Da Silva", sexo = 'm', foto = Resource.Drawable.morador178 });
            morador.Add(new Ceuense { id = 179, nome = "Max Leal De Freitas", sexo = 'm', foto = Resource.Drawable.morador179 });
            morador.Add(new Ceuense { id = 180, nome = "Michele Rodrigues Ferreira", sexo = 'f', foto = Resource.Drawable.morador180 });
            morador.Add(new Ceuense { id = 181, nome = "Miguel Cláudio Queiroz Rêgo", sexo = 'm', foto = Resource.Drawable.morador181 });
            //morador.Add(new Ceuense { id = 182, nome = "Miller Faustino Do Vale", sexo = 'm', foto = Resource.Drawable.morador182 });
            morador.Add(new Ceuense { id = 183, nome = "Miller Ribeiro Duarte", sexo = 'm', foto = Resource.Drawable.morador183 });
            //morador.Add(new Ceuense { id = 184, nome = "Nadyne Venturini Trindade", sexo = 'f', foto = Resource.Drawable.morador184 });
            //morador.Add(new Ceuense { id = 185, nome = "Neffer Arvey Gómez Gómez", sexo = 'm', foto = Resource.Drawable.morador185 });
            morador.Add(new Ceuense { id = 186, nome = "Nicolas Felipe Moço De Souza", sexo = 'm', foto = Resource.Drawable.morador186 });
            //morador.Add(new Ceuense { id = 187, nome = "Nilton Filipe Da Moura Cardoso", sexo = 'm', foto = Resource.Drawable.morador187 });
            morador.Add(new Ceuense { id = 188, nome = "Nivaldo Ramos Junior", sexo = 'm', foto = Resource.Drawable.morador188 });
            morador.Add(new Ceuense { id = 189, nome = "Nycaelly Sampaio Da Silva", sexo = 'f', foto = Resource.Drawable.morador189 });
            morador.Add(new Ceuense { id = 190, nome = "Orlando Monteiro Da Silva Neto", sexo = 'm', foto = Resource.Drawable.morador190 });
            morador.Add(new Ceuense { id = 191, nome = "Patricia De Lima Waltrick", sexo = 'f', foto = Resource.Drawable.morador191 });
            morador.Add(new Ceuense { id = 192, nome = "Patricia Verlindo Lemes", sexo = 'f', foto = Resource.Drawable.morador192 });
            morador.Add(new Ceuense { id = 193, nome = "Paulo Sérgio Beirão Junior", sexo = 'm', foto = Resource.Drawable.morador193 });
            morador.Add(new Ceuense { id = 194, nome = "Pedro Henrique Porto Osório", sexo = 'm', foto = Resource.Drawable.morador194 });
            morador.Add(new Ceuense { id = 195, nome = "Péliclis Nunes", sexo = 'm', foto = Resource.Drawable.morador195 });
            morador.Add(new Ceuense { id = 196, nome = "Pierre Bettim", sexo = 'm', foto = Resource.Drawable.morador196 });
            morador.Add(new Ceuense { id = 197, nome = "Priscila Mendes De Souza", sexo = 'f', foto = Resource.Drawable.morador197 });
            morador.Add(new Ceuense { id = 198, nome = "Rafaela Da Cruz Fávaro", sexo = 'f', foto = Resource.Drawable.morador198 });
            morador.Add(new Ceuense { id = 199, nome = "Rafaela Stefani Favaro Maes", sexo = 'f', foto = Resource.Drawable.morador199 });
            morador.Add(new Ceuense { id = 200, nome = "Rainan Costa Da Silva", sexo = 'm', foto = Resource.Drawable.morador200 });
            morador.Add(new Ceuense { id = 201, nome = "Raphael Dos Reis Tomaz", sexo = 'm', foto = Resource.Drawable.morador201 });
            morador.Add(new Ceuense { id = 202, nome = "Raquel Catarina Catani", sexo = 'f', foto = Resource.Drawable.morador202 });
            //morador.Add(new Ceuense { id = 203, nome = "Raylton Pereira De Sousa", sexo = 'm', foto = Resource.Drawable.morador203 });
            morador.Add(new Ceuense { id = 204, nome = "Rayssa Borges", sexo = 'f', foto = Resource.Drawable.morador204 });
            morador.Add(new Ceuense { id = 205, nome = "Rellydy Mahyara Dias Ferraz", sexo = 'f', foto = Resource.Drawable.morador205 });
            //morador.Add(new Ceuense { id = 206, nome = "Renalton Atanazio Cerqueira Filho", sexo = 'm', foto = Resource.Drawable.morador206 });
            morador.Add(new Ceuense { id = 207, nome = "Renan De Oliveira Bronhara", sexo = 'm', foto = Resource.Drawable.morador207 });
            morador.Add(new Ceuense { id = 208, nome = "Renato Antonio Ferreira Filho", sexo = 'm', foto = Resource.Drawable.morador208 });
            morador.Add(new Ceuense { id = 209, nome = "Renato Teixeira", sexo = 'm', foto = Resource.Drawable.morador209 });
            morador.Add(new Ceuense { id = 210, nome = "Ricardo Henrique Remes De Lima", sexo = 'm', foto = Resource.Drawable.morador210 });
            morador.Add(new Ceuense { id = 211, nome = "Ricardo Lima Da Silva", sexo = 'm', foto = Resource.Drawable.morador211 });
            morador.Add(new Ceuense { id = 212, nome = "Ricardo Manço Dutra", sexo = 'm', foto = Resource.Drawable.morador212 });
            morador.Add(new Ceuense { id = 213, nome = "Ricardo Scarmagnani", sexo = 'm', foto = Resource.Drawable.morador213 });
            morador.Add(new Ceuense { id = 214, nome = "Robson De Mattos Dos Santos Zeferino", sexo = 'm', foto = Resource.Drawable.morador214 });
            morador.Add(new Ceuense { id = 215, nome = "Rodolpho Lima Da Silva", sexo = 'm', foto = Resource.Drawable.morador215 });
            morador.Add(new Ceuense { id = 216, nome = "Rodrigo Leite Souza Enoque", sexo = 'm', foto = Resource.Drawable.morador216 });
            //morador.Add(new Ceuense { id = 217, nome = "Rodrigo Novack", sexo = 'm', foto = Resource.Drawable.morador217 });
            morador.Add(new Ceuense { id = 218, nome = "Rodrigo Potheski Da Luz", sexo = 'm', foto = Resource.Drawable.morador218 });
            morador.Add(new Ceuense { id = 219, nome = "Samara Oliveira Marques Da Silva", sexo = 'f', foto = Resource.Drawable.morador219 });
            //morador.Add(new Ceuense { id = 220, nome = "Sara Bodnar Rodrigues", sexo = 'f', foto = Resource.Drawable.morador220 });
            //morador.Add(new Ceuense { id = 221, nome = "Sara Godinho De Lima", sexo = 'f', foto = Resource.Drawable.morador221 });
            morador.Add(new Ceuense { id = 222, nome = "Silas Schneider Krause", sexo = 'm', foto = Resource.Drawable.morador222 });
            morador.Add(new Ceuense { id = 223, nome = "Stefany De Fátima Da Costa Alves", sexo = 'f', foto = Resource.Drawable.morador223 });
            morador.Add(new Ceuense { id = 224, nome = "Taisy Aparecida De Melo", sexo = 'f', foto = Resource.Drawable.morador224 });
            morador.Add(new Ceuense { id = 225, nome = "Thaís Andrade Brito", sexo = 'f', foto = Resource.Drawable.morador225 });
            morador.Add(new Ceuense { id = 226, nome = "Thais Da Glória Messias", sexo = 'f', foto = Resource.Drawable.morador226 });
            morador.Add(new Ceuense { id = 227, nome = "Thais Lara Guedes", sexo = 'f', foto = Resource.Drawable.morador227 });
            morador.Add(new Ceuense { id = 228, nome = "Thalita Lopes Mascarenhas", sexo = 'f', foto = Resource.Drawable.morador228 });
            morador.Add(new Ceuense { id = 229, nome = "Thays Da Silva Alves", sexo = 'f', foto = Resource.Drawable.morador229 });
            morador.Add(new Ceuense { id = 230, nome = "Thiago Atsushi Takashina", sexo = 'm', foto = Resource.Drawable.morador230 });
            morador.Add(new Ceuense { id = 231, nome = "Thiago Jessé Kucarz", sexo = 'm', foto = Resource.Drawable.morador231 });
            morador.Add(new Ceuense { id = 232, nome = "Thiozer Nunes De Morais", sexo = 'm', foto = Resource.Drawable.morador232 });
            morador.Add(new Ceuense { id = 233, nome = "Tiago Cícero Tumiski", sexo = 'm', foto = Resource.Drawable.morador233 });
            morador.Add(new Ceuense { id = 234, nome = "Tiago Grunhagen", sexo = 'm', foto = Resource.Drawable.morador234 });
            morador.Add(new Ceuense { id = 235, nome = "Tiago Schuarz", sexo = 'm', foto = Resource.Drawable.morador235 });
            //morador.Add(new Ceuense { id = 236, nome = "Valdecir Cândido Da Silva Junior", sexo = 'm', foto = Resource.Drawable.morador236 });
            morador.Add(new Ceuense { id = 237, nome = "Victor Anisio Alves Leão", sexo = 'm', foto = Resource.Drawable.morador237 });
            morador.Add(new Ceuense { id = 238, nome = "Vinicius Costa Martins", sexo = 'm', foto = Resource.Drawable.morador238 });
            morador.Add(new Ceuense { id = 239, nome = "Vitória Pereira Rosa", sexo = 'f', foto = Resource.Drawable.morador239 });
            //morador.Add(new Ceuense { id = 240, nome = "Wagner Carlesso Kowalski", sexo = 'm', foto = Resource.Drawable.morador240 });
            //morador.Add(new Ceuense { id = 241, nome = "Wagner Dos Santos Lima", sexo = 'm', foto = Resource.Drawable.morador241 });
            morador.Add(new Ceuense { id = 242, nome = "Wanessa Pocinhos Dos Santos", sexo = 'f', foto = Resource.Drawable.morador242 });
            morador.Add(new Ceuense { id = 243, nome = "Welligton Cassiano Portes", sexo = 'm', foto = Resource.Drawable.morador243 });
            //morador.Add(new Ceuense { id = 244, nome = "Wemerson Elias Costa Dos Prazeres", sexo = 'm', foto = Resource.Drawable.morador244 });
            morador.Add(new Ceuense { id = 245, nome = "Wesley Rodrigo Dos Santos", sexo = 'm', foto = Resource.Drawable.morador245 });
            morador.Add(new Ceuense { id = 246, nome = "Wilham Klevis De Queiroz", sexo = 'm', foto = Resource.Drawable.morador246 });
            morador.Add(new Ceuense { id = 247, nome = "Yenifer Ninosca Silva Segovia", sexo = 'f', foto = Resource.Drawable.morador247 });
            #endregion
            return morador;
        }
    }
}